# 'Allow scripts to access the OAuth token' was selected in pipeline.  Add the following YAML to any steps requiring access:
#       env:
#           MY_ACCESS_TOKEN: $(System.AccessToken)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchDepth: 1
    persistCredentials: True
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: >-
        echo Write your commands here

        echo Hello world

        "$(Build.SourcesDirectory)\App\ProgramFiles\bin\x86\advinst.exe" /execute "$(Build.SourcesDirectory)\outputs\project.aip" "$(Build.SourcesDirectory)\outputs\project.ini"

        git config --global user.email "you@example.com"

        git config --global user.name "Your Name"

        git add .

        git commit -m "build success"

        git push origin HEAD:main
...
